/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: Ole Gunnar Isager (https://sketchfab.com/FrenchBaguette)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/robot-cln-r-school-project-9a793a9293fb4ec89936aebfda8fc434
Title: Robot CLN-R (School Project)
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function ModelThree(props) {
  const { nodes, materials } = useGLTF('./robot_cln-r_school_project/scene.gltf')
  return (
    <group {...props} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.pCube43_lambert4_0.geometry}
        material={materials.lambert4}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.pCube43_MetalShiny_0.geometry}
        material={materials.MetalShiny}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.pCube43_Rubber_0.geometry}
        material={materials.Rubber}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.pCube43_Metal_0.geometry}
        material={materials.Metal}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.pCube43_lambert1_0.geometry}
        material={materials.lambert1}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.pCube43_pasted__Eyes_0.geometry}
        material={materials.pasted__Eyes}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.pCube43_BlackGlass_0.geometry}
        material={materials.BlackGlass}
      />
    </group>
  )
}

useGLTF.preload('./robot_cln-r_school_project/scene.gltf')
export default ModelThree;

