/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: cyborgin (https://sketchfab.com/cyborgin)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/robot-2872b9d25b894e8bb494c069207c4802
Title: Robot
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Modelone(props) {
    const { nodes, materials } = useGLTF('./robot/scene.gltf')
    return (
        <group {...props} dispose={null}>
            <group rotation={[-Math.PI / 2, 0, 0]} scale={0.001}>
                <group rotation={[Math.PI / 2, 0, 0]}>
                    <group position={[31.798, 1172.188, 100.274]} rotation={[Math.PI / 2, 0, -Math.PI]}>
                        <mesh
                            castShadow
                            receiveShadow
                            geometry={nodes['����������������3-DC_Shell001_01_-_Default_0'].geometry}
                            material={materials['01_-_Default']}
                        />
                        <mesh
                            castShadow
                            receiveShadow
                            geometry={nodes['����������������3-DC_Shell001_01_-_Default_0_1'].geometry}
                            material={materials['01_-_Default']}
                        />
                        <mesh
                            castShadow
                            receiveShadow
                            geometry={nodes['����������������3-DC_Shell001_01_-_Default_0_2'].geometry}
                            material={materials['01_-_Default']}
                        />
                        <mesh
                            castShadow
                            receiveShadow
                            geometry={nodes['����������������3-DC_Shell001_01_-_Default_0_3'].geometry}
                            material={materials['01_-_Default']}
                        />
                        <mesh
                            castShadow
                            receiveShadow
                            geometry={nodes['����������������3-DC_Shell001_01_-_Default_0_4'].geometry}
                            material={materials['01_-_Default']}
                        />
                        <mesh
                            castShadow
                            receiveShadow
                            geometry={nodes['����������������3-DC_Shell001_Material_#6_0'].geometry}
                            material={materials.Material_6}
                        />
                        <mesh
                            castShadow
                            receiveShadow
                            geometry={nodes['����������������3-DC_Shell001_09_-_Default_0'].geometry}
                            material={materials['09_-_Default']}
                        />
                        <mesh
                            castShadow
                            receiveShadow
                            geometry={nodes['����������������3-DC_Shell001_����_0'].geometry}
                            material={materials.material}
                        />
                        <mesh
                            castShadow
                            receiveShadow
                            geometry={nodes['����������������3-DC_Shell001_10_-_D��������_0'].geometry}
                            material={materials['10_-_D']}
                        />
                        <mesh
                            castShadow
                            receiveShadow
                            geometry={nodes['����������������3-DC_Shell001_Steel_0'].geometry}
                            material={materials.Steel}
                        />
                        <mesh
                            castShadow
                            receiveShadow
                            geometry={nodes['����������������3-DC_Shell001_20_-_Default_0'].geometry}
                            material={materials['20_-_Default']}
                        />
                        <mesh
                            castShadow
                            receiveShadow
                            geometry={nodes['����������������3-DC_Shell001_08_-_Default_0'].geometry}
                            material={materials['08_-_Default']}
                        />
                        <mesh
                            castShadow
                            receiveShadow
                            geometry={nodes['����������������3-DC_Shell001_Material_#26_0'].geometry}
                            material={materials.Material_26}
                        />
                        <mesh
                            castShadow
                            receiveShadow
                            geometry={nodes['����������������3-DC_Shell001_Material_#26_0_1'].geometry}
                            material={materials.Material_26_0}
                        />
                        <mesh
                            castShadow
                            receiveShadow
                            geometry={nodes['����������������3-DC_Shell001_Material_#12_0'].geometry}
                            material={materials.Material_12}
                        />
                        <mesh
                            castShadow
                            receiveShadow
                            geometry={nodes['����������������3-DC_Shell001_05_-_Default_0'].geometry}
                            material={materials['05_-_Default']}
                        />
                        <mesh
                            castShadow
                            receiveShadow
                            geometry={nodes['����������������3-DC_Shell001_22_0'].geometry}
                            material={materials.material_12}
                        />
                        <mesh
                            castShadow
                            receiveShadow
                            geometry={nodes['����������������3-DC_Shell001_Material_#11_0'].geometry}
                            material={materials.Material_11}
                        />
                        <mesh
                            castShadow
                            receiveShadow
                            geometry={nodes['����������������3-DC_Shell001_Material_#21_0'].geometry}
                            material={materials.Material_21}
                        />
                        <mesh
                            castShadow
                            receiveShadow
                            geometry={nodes['����������������3-DC_Shell001_Steel2_0'].geometry}
                            material={materials.Steel2}
                        />
                        <mesh
                            castShadow
                            receiveShadow
                            geometry={nodes['����������������3-DC_Shell001_Material_#4_0'].geometry}
                            material={materials.Material_4}
                        />
                        <mesh
                            castShadow
                            receiveShadow
                            geometry={nodes['����������������3-DC_Shell001_07_-_Default_0'].geometry}
                            material={materials['07_-_Default']}
                        />
                    </group>
                </group>
            </group>
        </group>
    )
}

useGLTF.preload('./robot/scene.gltf')
export default Modelone